#!/usr/bin/env sh
#
# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Paul Scheffler <paulsc@iis.ee.ethz.ch>

# Run DUTCTL directly using system Python 3 (include src in path)
PYTHONPATH="${PYTHONPATH}:$(dirname "$(realpath "$0")")/src" /usr/bin/env python3 -m dutctl "$@"
