# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Paul Scheffler <paulsc@iis.ee.ethz.ch>
# Thomas Benz <tbenz@iis.ee.ethz.ch>

# Example netplan configuration for static IPs for network-attached lab devices.
# Copy this file to `/etc/netplan/01-occamy-supplies.yaml`

network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enx00e04c680acf:
      dhcp4: no
      addresses: [169.254.21.49/16]
