# Copyright 2025 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Paul Scheffler <paulsc@iis.ee.ethz.ch>
# Thomas Benz <tbenz@iis.ee.ethz.ch>

# Instrument configuration for dutctl.
# WARNING: Changing these values has real electrical effects on connected DUTs,
# including potential death; check your config with no DUT unconnected first!

# If the remaining config doesn't hash to `safety_hash`, `dutctl` rejects it as
# a safety measure. You can bypass this with `0xd0a515a1` at your own risk.
safety_hash: 0x3815dc8d675dff07

siggens: {}

supplies_ganged: true

supplies:

  E36312A_1:
    ip: 169.254.12.1
    reset_gpio: 1
    channels:
      1: {vol: 1.8, cur: 0.1}

  E36231A_1:
    ip: 169.254.31.1
    channels:
      0: {vol: 1.2, cur: 0.5, volmin: 0.75, volmax: 1.35, measure: true}
